import { Wysiwyg } from '@/components/custom/wysiwyg';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Head } from '@inertiajs/react';
import { useState } from 'react';

export default function WysiwygDemo() {
    const [content, setContent] = useState(
        '<p>Hello <strong>World</strong>! This is a <em>demo</em> of the WYSIWYG editor.</p>'
    );
    const [output, setOutput] = useState('');

    const handleContentChange = (newContent: string) => {
        setContent(newContent);
    };

    const handleGetContent = () => {
        setOutput(content);
    };

    const handleClear = () => {
        setContent('');
        setOutput('');
    };

    return (
        <>
            <Head title="WYSIWYG Demo" />

            <div className="container mx-auto space-y-8 py-8">
                <div className="text-center">
                    <h1 className="text-3xl font-bold">WYSIWYG Editor Demo</h1>
                    <p className="text-muted-foreground mt-2">
                        A rich text editor built with Tiptap and React
                    </p>
                </div>

                <div className="grid grid-cols-1 gap-8 lg:grid-cols-2">
                    {/* Editor Section */}
                    <Card>
                        <CardHeader>
                            <CardTitle>Editor</CardTitle>
                            <CardDescription>
                                Try typing and formatting text using the toolbar
                            </CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <Wysiwyg
                                content={content}
                                onChange={handleContentChange}
                                minHeight="300px"
                                maxHeight="500px"
                                className="w-full"
                            />

                            <div className="flex gap-2">
                                <Button onClick={handleGetContent}>Get Content</Button>
                                <Button variant="outline" onClick={handleClear}>
                                    Clear
                                </Button>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Output Section */}
                    <Card>
                        <CardHeader>
                            <CardTitle>Output</CardTitle>
                            <CardDescription>
                                The HTML content generated by the editor
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="space-y-4">
                                <div>
                                    <h4 className="mb-2 font-medium">HTML Output:</h4>
                                    <pre className="bg-muted max-h-64 overflow-auto rounded-md p-4 text-sm">
                                        {output || 'Click "Get Content" to see the HTML output'}
                                    </pre>
                                </div>

                                <div>
                                    <h4 className="mb-2 font-medium">Rendered Output:</h4>
                                    <div
                                        className="min-h-32 rounded-md border p-4"
                                        dangerouslySetInnerHTML={{
                                            __html:
                                                output ||
                                                'Click "Get Content" to see the rendered output',
                                        }}
                                    />
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* Features Section */}
                <Card>
                    <CardHeader>
                        <CardTitle>Features</CardTitle>
                        <CardDescription>
                            This WYSIWYG editor includes the following features:
                        </CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
                            <div className="space-y-2">
                                <h4 className="font-medium">Text Formatting</h4>
                                <ul className="text-muted-foreground space-y-1 text-sm">
                                    <li>• Bold, Italic, Underline</li>
                                    <li>• Strikethrough, Code</li>
                                    <li>• Headings (H1, H2, H3)</li>
                                </ul>
                            </div>

                            <div className="space-y-2">
                                <h4 className="font-medium">Lists & Blocks</h4>
                                <ul className="text-muted-foreground space-y-1 text-sm">
                                    <li>• Bullet Lists</li>
                                    <li>• Numbered Lists</li>
                                    <li>• Blockquotes</li>
                                    <li>• Code Blocks</li>
                                </ul>
                            </div>

                            <div className="space-y-2">
                                <h4 className="font-medium">User Experience</h4>
                                <ul className="text-muted-foreground space-y-1 text-sm">
                                    <li>• Floating Menu</li>
                                    <li>• Bubble Menu</li>
                                    <li>• Undo/Redo</li>
                                    <li>• Keyboard Shortcuts</li>
                                </ul>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </>
    );
}
